// This file is intentionally empty - DataTableNodeSchema is now fully auto-generated.
// See: packages/dsl-ui/src/schemas/generated-node-schemas.ts
// Generated by: packages/dsl-ui/scripts/generate-node-schemas.ts
