name: CI / Publish

on:
    push:
        branches: [main]
    pull_request:
    workflow_dispatch:
        inputs:
            version:
                description: 'Stable version (e.g. 1.2.0)'
                required: false
                default: ''
            breaking:
                description: 'Breaking change? (true/false)'
                required: false
                default: 'false'

jobs:
    publish-dsl-renderer:
        if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
        uses: wadeck-app/ci-templates/.github/workflows/publish-npm.yml@main
        secrets: inherit
        with:
            workspace: packages/dsl-renderer
            bundle-script: ''
            version-input: ${{ inputs.version || '' }}
            breaking-input: ${{ inputs.breaking || 'false' }}

    publish-dsl-ui:
        if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
        uses: wadeck-app/ci-templates/.github/workflows/publish-npm.yml@main
        secrets: inherit
        with:
            workspace: packages/dsl-ui
            bundle-script: ''
            version-input: ${{ inputs.version || '' }}
            breaking-input: ${{ inputs.breaking || 'false' }}
